# permissions for end users to view microvms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: microvm-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: microvm-operator
    app.kubernetes.io/part-of: microvm-operator
    app.kubernetes.io/managed-by: kustomize
  name: microvm-viewer-role
rules:
- apiGroups:
  - infrastructure.liquid-metal.io
  resources:
  - microvms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.liquid-metal.io
  resources:
  - microvms/status
  verbs:
  - get
