# permissions for end users to view microvmtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: microvmtemplate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: microvm-operator
    app.kubernetes.io/part-of: microvm-operator
    app.kubernetes.io/managed-by: kustomize
  name: microvmtemplate-viewer-role
rules:
- apiGroups:
  - infrastructure.flintlock.x-k8s.io
  resources:
  - microvmtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.flintlock.x-k8s.io
  resources:
  - microvmtemplates/status
  verbs:
  - get
