# permissions for end users to edit microvmdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: microvmdeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: microvm-operator
    app.kubernetes.io/part-of: microvm-operator
    app.kubernetes.io/managed-by: kustomize
  name: microvmdeployment-editor-role
rules:
- apiGroups:
  - infrastructure.liquid-metal.io
  resources:
  - microvmdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.liquid-metal.io
  resources:
  - microvmdeployments/status
  verbs:
  - get
