# permissions for end users to edit microvmreplicasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: microvmreplicaset-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: microvm-operator
    app.kubernetes.io/part-of: microvm-operator
    app.kubernetes.io/managed-by: kustomize
  name: microvmreplicaset-editor-role
rules:
- apiGroups:
  - infrastructure.flintlock.x-k8s.io
  resources:
  - microvmreplicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.flintlock.x-k8s.io
  resources:
  - microvmreplicasets/status
  verbs:
  - get
