---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - infrastructure.liquid-metal.io
  resources:
  - microvmreplicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.liquid-metal.io
  resources:
  - microvmreplicasets/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.liquid-metal.io
  resources:
  - microvmreplicasets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infrastructure.liquid-metal.io
  resources:
  - microvms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.liquid-metal.io
  resources:
  - microvms/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.liquid-metal.io
  resources:
  - microvms/status
  verbs:
  - get
  - patch
  - update
